name: benchmarks
channels:
  - conda-forge
dependencies:
  - numpy
  - cma==3.2.2
  - scikit-learn
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - pip
  - pip:
    - nevergrad
    - torch
    - autorank
